// Generated by gencpp from file service_hw/first_srv.msg
// DO NOT EDIT!


#ifndef SERVICE_HW_MESSAGE_FIRST_SRV_H
#define SERVICE_HW_MESSAGE_FIRST_SRV_H

#include <ros/service_traits.h>


#include <service_hw/first_srvRequest.h>
#include <service_hw/first_srvResponse.h>


namespace service_hw
{

struct first_srv
{

typedef first_srvRequest Request;
typedef first_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct first_srv
} // namespace service_hw


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_hw::first_srv > {
  static const char* value()
  {
    return "f7c050886f579d8f0fea8a64fe57628a";
  }

  static const char* value(const ::service_hw::first_srv&) { return value(); }
};

template<>
struct DataType< ::service_hw::first_srv > {
  static const char* value()
  {
    return "service_hw/first_srv";
  }

  static const char* value(const ::service_hw::first_srv&) { return value(); }
};


// service_traits::MD5Sum< ::service_hw::first_srvRequest> should match 
// service_traits::MD5Sum< ::service_hw::first_srv > 
template<>
struct MD5Sum< ::service_hw::first_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_hw::first_srv >::value();
  }
  static const char* value(const ::service_hw::first_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_hw::first_srvRequest> should match 
// service_traits::DataType< ::service_hw::first_srv > 
template<>
struct DataType< ::service_hw::first_srvRequest>
{
  static const char* value()
  {
    return DataType< ::service_hw::first_srv >::value();
  }
  static const char* value(const ::service_hw::first_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_hw::first_srvResponse> should match 
// service_traits::MD5Sum< ::service_hw::first_srv > 
template<>
struct MD5Sum< ::service_hw::first_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_hw::first_srv >::value();
  }
  static const char* value(const ::service_hw::first_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_hw::first_srvResponse> should match 
// service_traits::DataType< ::service_hw::first_srv > 
template<>
struct DataType< ::service_hw::first_srvResponse>
{
  static const char* value()
  {
    return DataType< ::service_hw::first_srv >::value();
  }
  static const char* value(const ::service_hw::first_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_HW_MESSAGE_FIRST_SRV_H
