// Generated by gencpp from file service_hw/first_srvResponse.msg
// DO NOT EDIT!


#ifndef SERVICE_HW_MESSAGE_FIRST_SRVRESPONSE_H
#define SERVICE_HW_MESSAGE_FIRST_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_hw
{
template <class ContainerAllocator>
struct first_srvResponse_
{
  typedef first_srvResponse_<ContainerAllocator> Type;

  first_srvResponse_()
    : ans(0)  {
    }
  first_srvResponse_(const ContainerAllocator& _alloc)
    : ans(0)  {
  (void)_alloc;
    }



   typedef int32_t _ans_type;
  _ans_type ans;





  typedef boost::shared_ptr< ::service_hw::first_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_hw::first_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct first_srvResponse_

typedef ::service_hw::first_srvResponse_<std::allocator<void> > first_srvResponse;

typedef boost::shared_ptr< ::service_hw::first_srvResponse > first_srvResponsePtr;
typedef boost::shared_ptr< ::service_hw::first_srvResponse const> first_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_hw::first_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_hw::first_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace service_hw

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::service_hw::first_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_hw::first_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_hw::first_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_hw::first_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_hw::first_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_hw::first_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_hw::first_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd5d0466a761324f0f90b3b2afef3d69";
  }

  static const char* value(const ::service_hw::first_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd5d0466a761324fULL;
  static const uint64_t static_value2 = 0x0f90b3b2afef3d69ULL;
};

template<class ContainerAllocator>
struct DataType< ::service_hw::first_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_hw/first_srvResponse";
  }

  static const char* value(const ::service_hw::first_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_hw::first_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ans\n\
";
  }

  static const char* value(const ::service_hw::first_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_hw::first_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ans);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct first_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_hw::first_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_hw::first_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "ans: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ans);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_HW_MESSAGE_FIRST_SRVRESPONSE_H
